### ISSUE TITLE
Could you add a license?

### ISSUE THREAD

**Issue by Benbentwo** [dvmtn/datadog-notify#4]
Hoping to use some of this code to help send events to datadog. With no license, it follows the default, which means no derivative works can be created. If this is intended a license would help clarify!

References:
 - https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by AdamWhittingham** [comment]
Thanks for the helpful link - I've added the MIT license 👍
